apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: se350-03.edge.lab
  namespace: openshift-machine-api
spec:
  automatedCleaningMode: metadata
  bmc:
    address: redfish-virtualmedia://se350-03-xcc.edge.lab/redfish/v1/Systems/1
    credentialsName: se350-03-bmc-secret
    disableCertificateVerification: true
  bootMACAddress: 08:3a:88:1e:0e:dd
  online: true
