apiVersion: v1
kind: Secret
metadata:
  labels:
    environment.metal3.io: baremetal
  name: se350-generic-bmc-secret
  namespace: openshift-machine-api
stringData:
  password: user
  username: password
type: Opaque
