apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: se350-04.edge.lab
  namespace: openshift-machine-api
spec:
  automatedCleaningMode: metadata
  bmc:
    address: redfish-virtualmedia://se350-04-xcc.edge.lab/redfish/v1/Systems/1
    credentialsName: se350-04-bmc-secret
    disableCertificateVerification: true
  bootMACAddress: 04:7b:cb:8b:b2:36
  online: true
