apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: se350-generic-bmc-secret
  namespace: openshift-machine-api
spec:
  encryptedData:
    password: AgAbrqiQZF1r1cTv6faNcMT6Wyx0JFnDGsEGYROi1qeoXORzwOwF42vnvoa+T3dQIJ7Brrwif5lMwnAOlQqFvCp/Kp2sr3IwDvIx+unIz3rAhaepzLcItxdyM3lYB0eYTSS3mV4Tvpj4BjpJJXgyIAilm3djltBQ63FIdRg5lcpB6LhcE2ulB65OuU/RoAHwtkFd4k3aj5nOS7oi7yBjRvhmtoB3I3R0tORxSgjqVotKxZxzBfZP3HKJ8VY0RqkXZnT+tumyvNqt2sMSqVL+xEr13b13GNN/hM6GzUliqLXrSADKyCKH7mehfioKRk7itIf6X6NJ2EP6Fz6f+Ozo2NxBnY3SoabS4wang8WFc+myXPw6Gn+qVAEDTcNGmbKU92hmvx6g5rFOA774G4/yh/XT35gwtrLZ8OxNpgJzNTCxVJTxGLfx7CpSavqbj5IQOyBvdZau2EY3je6ZdZtxjffqZnDJuhTwyUl+LDWxxPixlWA+GI0put/DYh0wf0lcdfmEnA9wAQfK4Xek5wcyj2BLQsDkhxlAEwz+piJZMzSh0WwHoUMaCgUuPlPK+xISOLWXktP66fItywJAFc9j2IEqZuG78IRXgjYwDkLLo/g9O5a/dmsima+NzBHXK+hT/nHD6qeZdT4B/9Yc1ktwSkptQOnUbPXENrg0hJPYwHOY6rIJeYowYLjYjMVbUa8rPVqRQ1NFfUahX7VI
    username: AgBXDBrFaDzHeW5T+mGq8bnLRsnbxyDD1w3iH/FR5C1CoUjqRGI4fPXE4QLRqHHgWImZ79pXLk3s5t8PFs/elS1U68GLhBlrM5jHAmorATnuJ0vrYIj0HoZDbHmBmrHfaOInbJOZCg9nNwfo/yTFTbmnrr5YWHDtv/jIrgpQ0iEtKa0MTTiLdkn30NHENSEetLfOaqLFUJcPX6kebngwBitGeqJZ7YMs2dPxo+Ui+JV+KTYuvCnhPkqcm8sKjo9z4GGskgcbVhHNxmqC4yoKg0qsZGq+D+0s8YjocDXVKMgh01dvKA0QvkZR77MBxLcGG2WlLf/y+d1gS+9D6zwS/dEUajGPJygdsQDJVF+ntZ66SXONRjX5U578z573uMClmG8h1cVn674FPzXBHtfFSLqCVandRdl1TVIz8AEGXXzgJj0VVoo9ANCj8otuBECbACJZg48GuLaQwPF4RBU1xsPD80x7G7v+NAfe9hzNm8/gvDhwQ0Ro2Aic+amB74KRZcvPrSDSOUV0DSr/szjJN4pg+Lh5jcyjk+TmBGb6mAaROCxOEULKvdj3g94Ai9b7kxpKc7j9ybczYntshIfbx6h4FOxn0LHYTybNtacvxyKzVIbQ/DHbv8MzGe0zAqNgZy6Oeds5uQp8V+024JIqcKVFH4x16HXqYJICtrNnIxje2bQ3aH5rMKKMsJbsVHNQrXSAc/YjWIM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        environment.metal3.io: baremetal
      name: se350-generic-bmc-secret
      namespace: openshift-machine-api
    type: Opaque
