apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
  - ../../../components/argocd/apps/overlays/default

patches:
  - path: patch-applicationset-repo-revision.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      kind: Application
  # Uncomment patches to disable automatic sync
  # - path: patch-applicationset-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     kind: ApplicationSet
  # - path: patch-application-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     kind: Application
