apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sleeper-admin
  name: sleeper-admin
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: sleeper-admin
  selector:
    matchLabels:
      app.kubernetes.io/name: sleeper-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sleeper-admin
    spec:
      serviceAccount: cluster-admin-adhoc-helper
      serviceAccountName: cluster-admin-adhoc-helper
      automountServiceAccountToken: false
      containers:
        - command:
          - sh
          - -c
          - |
            #!/bin/sh
            echo "Where we are going we don't need kubeadmin!"
            echo ""
            echo "You have found the hidden chamber! Now what?"

            sleep 600
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          name: tools
          resources:
            limits:
              cpu: 400m
              memory: 64Mi
          volumeMounts:
            - mountPath: /run/kubernetes.io/serviceaccount/token
              name: sa-token
      volumes:
        - name: sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: sa-token
                  expirationSeconds: 1200
