---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-compute
spec:
  hard:
    # requests.cpu: '1'
    # requests.memory: 1Gi
    limits.cpu: '32'
    limits.memory: 128Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-storage
spec:
  hard:
    requests.storage: 20Gi
    persistentvolumeclaims: '40'
