apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"

resources:
  - ../../../operators/t8c-certified/operator/overlays/stable
  - ../../../operators/kubeturbo-certified/operator/overlays/stable

patches:
  - target:
      kind: OperatorGroup
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value:
          - turbo
