---
kind: Service
apiVersion: v1
metadata:
  name: example
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: example
subsets:
  - addresses:
      - ip: 192.168.10.100
    ports:
      - port: 443
        protocol: TCP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: example
spec:
  to:
    kind: Service
    name: example
    weight: 100
  port:
    targetPort: 443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None