kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-cluster-virt-editors
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: lab-cluster-virt-editors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: os-images.kubevirt.io:edit