apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - app-local-storage.yaml
  - app-odf-instance.yaml
  - app-pgadmin4.yaml
  - appset-tenants.yaml

patches:
  - target:
      group: argoproj.io
      kind: Application
      name: cluster-config-app-of-apps
    path: patch-cluster-config-app-of-apps.yaml
  - target:
      group: argoproj.io
      kind: ApplicationSet
      name: cluster-configs-applicationset
    path: patch-configs-applicationset.yaml
  - target:
      group: argoproj.io
      kind: ApplicationSet
      name: cluster-operators-applicationset
    path: patch-operators-applicationset.yaml
